const sidebars = {
  ezoSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Snippets',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'snippets',
        },
      ],
    },
  ],
};

module.exports = sidebars;
